
alter table newr_repos.plan_balance add(active_status_loan_balance NUMBER(17, 2));


alter table newr_repos.plan_balance_monthly add(active_status_loan_balance NUMBER(17, 2));
alter table newr_repos.plan_balance_monthly_delta add(active_status_loan_balance NUMBER(17, 2));

alter table newr_repos.plan_balance_quarterly add(active_status_loan_balance NUMBER(17, 2));
alter table newr_repos.plan_balance_quarterly_delta add(active_status_loan_balance NUMBER(17, 2));

drop table newr_repos.PARTICIPANT_FUND_BALANCE;
CREATE TABLE NEWR_REPOS.PARTICIPANT_FUND_BALANCE
(
client_id VARCHAR2(25 BYTE) NOT NULL ,
PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL 
, PARTICIPANT_ID VARCHAR2(25 BYTE) NOT NULL 
, FUND_NUMBER VARCHAR2(15 BYTE) NOT NULL 
, FUND_IV VARCHAR2(10 BYTE) NOT NULL 
, CASH_VALUE_AMOUNT NUMBER(17, 2) 
, TOTAL_UNITS NUMBER(17, 4) 
, SHARE_PRICE NUMBER(17, 6) 
, EE_CASH_VALUE_AMOUNT NUMBER(17, 2) 
, ER_CASH_VALUE_AMOUNT NUMBER(17, 2) 
, YTD_CONTRIBUTIONS NUMBER(17, 2) 
, SOURCE_CYCLE_DATE DATE NOT NULL 
, RETIREMENT_ACCOUNT_ID VARCHAR2(40 BYTE) NOT NULL 	,
CONSTRAINT PK_PARTICIPANT_FUND_BALANCE PRIMARY KEY 
(client_id,
PLAN_NUMBER,
  PARTICIPANT_ID 
, RETIREMENT_ACCOUNT_ID  
, FUND_NUMBER 
, FUND_IV
, SOURCE_CYCLE_DATE 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;

--- GRANT PARTICIPANT_FUND_BALANCE
GRANT SELECT ON NEWR_REPOS.PARTICIPANT_FUND_BALANCE TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOS.PARTICIPANT_FUND_BALANCE TO role_newr_repos_write;



-----NEWR_REPOSB
alter table newr_reposb.plan_balance add(active_status_loan_balance NUMBER(17, 2));
drop table newr_reposb.PARTICIPANT_FUND_BALANCE;
CREATE TABLE NEWR_REPOSb.PARTICIPANT_FUND_BALANCE
(
client_id VARCHAR2(25 BYTE) NOT NULL ,
PLAN_NUMBER VARCHAR2(25 BYTE) NOT NULL 
, PARTICIPANT_ID VARCHAR2(25 BYTE) NOT NULL 
, RETIREMENT_ACCOUNT_ID VARCHAR2(40 BYTE) NOT NULL 
, FUND_NUMBER VARCHAR2(15 BYTE) NOT NULL 
, FUND_IV VARCHAR2(10 BYTE) NOT NULL 
, CASH_VALUE_AMOUNT NUMBER(17, 2) 
, TOTAL_UNITS NUMBER(17, 4) 
, SHARE_PRICE NUMBER(17, 6) 
, EE_CASH_VALUE_AMOUNT NUMBER(17, 2) 
, ER_CASH_VALUE_AMOUNT NUMBER(17, 2) 
, YTD_CONTRIBUTIONS NUMBER(17, 2) 
, SOURCE_CYCLE_DATE DATE NOT NULL ,
CONSTRAINT PK_PARTICIPANT_FUND_BALANCE PRIMARY KEY 
(client_id,
PLAN_NUMBER,
  PARTICIPANT_ID 
, RETIREMENT_ACCOUNT_ID  
, FUND_NUMBER 
, FUND_IV
, SOURCE_CYCLE_DATE 
)
USING INDEX
TABLESPACE NEWR_REPOS_INDEX
)
TABLESPACE NEWR_REPOS_DATA
;

--- GRANT PARTICIPANT_FUND_BALANCE
GRANT SELECT ON NEWR_REPOSb.PARTICIPANT_FUND_BALANCE TO role_newr_repos_read;
GRANT INSERT, UPDATE, DELETE ON NEWR_REPOSb.PARTICIPANT_FUND_BALANCE TO role_newr_repos_write;