
from pyspark.sql import SparkSession
from pyspark.sql.functions import *


def transform(spark: SparkSession, batch_date: str, primary_key: list):

    consumption_df = spark.sql("select  coalesce(plan_number,'-9999') as plan_number, coalesce(run_date,current_date()-1) as run_date, coalesce(base_transaction_code,'-9999') as base_transaction_code, coalesce(rev_code,'-9999') as rev_code, coalesce(pay_period_end_date,current_date()-1) as pay_period_end_date, coalesce(trade_date,current_date()-1) as trade_date, coalesce(div_sub_id,'-9999') as div_sub_id, cast(coalesce(total_transaction,0) as INTEGER) as  total_transaction, cast(coalesce(total_cash_amount,0) as DECIMAL(17,2)) as total_cash_amount, cast(coalesce(total_unit_shares,0) as DECIMAL(17,2)) as total_unit_shares, cast(coalesce(total_share_price,0) as DECIMAL(17,2)) as total_share_price, cast(coalesce(total_unique_participant,0) as INTEGER) as  total_unique_participant from (select   txn.plan_number,   txn.run_date,   txn.base_transaction_code,   txn.pay_period_end_date,   txn.rev_code,   txn.trade_date,   case when txn.div_sub_id='' then '-9999' else txn.div_sub_id end as div_sub_id,   t.total_transaction,   t.total_cash_amount,   t.total_unit_shares,   t.total_share_price,   t.total_unique_participant,   ch.mo_last_business_day   from   (select plan_number,case             when div_sub_id = '' then '-9999'             else div_sub_id           end as div_sub_id, run_date,pay_period_end_date,rev_code,base_transaction_code,trade_date,count(1) from txn group by plan_number,div_sub_id, run_date,pay_period_end_date,rev_code,base_transaction_code,trade_date  ) as txn           left outer join   (     select       plan_number,       div_sub_id,       run_date,       count(distinct(participant_id)) as total_unique_participant,       count(base_transaction_code) as total_transaction,       sum(coalesce(cash,0)) as total_cash_amount ,       sum(coalesce(shares,0))as total_unit_shares,       sum(coalesce(share_price,0)) as total_share_price     from(         select           plan_number,case             when div_sub_id = '' then '-9999'             else div_sub_id           end as div_sub_id,           run_date,           base_transaction_code,           participant_id,           cash,           shares,           share_price         from           txn       )     group by       plan_number,       div_sub_id,       run_date   ) as t   On   coalesce(txn.plan_number,'-9999')=coalesce(t.plan_number,'-9999') and coalesce(txn.div_sub_id,'-9999')=coalesce(t.div_sub_id,'-9999')    and coalesce(txn.run_date,current_date()-1)=coalesce(t.run_date,current_date()-1)   left outer join calendar_helper ch    on  coalesce(t.run_date,current_date()-1)=coalesce(ch.mo_last_business_day,current_date()-1))")

    return consumption_df