from wealthcentral.jobs.staging_to_raw.schemas import (
    plan_vnq_wc_txt_schema,
    participant_investment_product_election_vnq_wc_txt_schema,
    setit_plan_daily_wc_dat_txt_schema,
    participant_vnq_wc_txt_schema,
    participant_investment_election_vnq_wc_txt_schema,
    employer_vnq_wc_txt_schema,
    beneficiary_vnq_wc_txt_schema,
    transaction_vnq_wc_txt_schema,
    participant_distribution_vnq_wc_txt_schema,
    participant_fund_vnq_wc_txt_schema,
    participant_fund_vnq_wc_hist_txt_schema,
    participant_contribution_vnq_wc_txt_schema,
    super_omni_newr_plan_daily_ng_dat_schema,
    super_omni_newr_plan_daily_jb_dat_schema,
    super_omni_newr_bene_daily_ng_dat_schema,
    super_omni_newr_bene_daily_jb_dat_schema,
    exn_xxewre01_xxewrptd_jb_schema,
    transaction_type_csv_schema,
    super_omni_newr_seqhist_daily_ng_dat_schema,
    super_omni_newr_seqhist_daily_jb_dat_schema,
    super_omni_newr_plan_mindist_daily_ng_dat_schema,
    super_omni_newr_plan_ins_daily_ng_dat_schema,
    super_omni_newr_plan_divsub_daily_ng_dat_schema,
    super_omni_newr_planwdrl_daily_ng_dat_schema,
    super_omni_newr_planwdrl_daily_jb_dat_schema,
    super_omni_newr_planvesting_daily_ng_dat_schema,
    super_omni_newr_planvesting_daily_jb_dat_schema,
    super_omni_newr_partsrcval_daily_ng_dat_schema,
    super_omni_newr_particpantaccount_daily_ng_dat_schema,
    super_omni_newr_particpantaccount_daily_jb_dat_schema,
    super_omni_newr_partgaabal_monthly_ng_dat_schema,
    super_omni_newr_partacctms_daily_ng_dat_schema,
    super_omni_newr_partacctms_daily_jb_dat_schema,
    super_omni_newr_loanval_daily_ng_dat_schema,
    super_omni_newr_lifeval_monthly_ng_dat_schema,
    super_omni_newr_histbal_ng_dat_schema,
    super_omni_newr_histbal_jb_dat_schema,
    stars_daily_contact_dat_schema,
    ssn_output_ng_schema,
    ssn_output_jb_schema,
    slx_tpa_common_daily_dat_schema,
    presto_plan_daily_dat_schema,
    premier_fund_translation_csv_schema,
    pdab_sponsor_csv_schema,
    pdab_role_code_helper_csv_schema,
    pdab_product_helper_csv_schema,
    pdab_money_source_helper_csv_schema,
    pdab_market_segment_csv_schema,
    pdab_auto_method_csv_schema,
    pdab_automation_type_csv_schema,
    ods_retirement_account_schema,
    nw00paap_nldss_prdps_ps50_prdcrext_lx_seq_schema,
    nw00paap_nlarc_prdps_plan_pdab_data_schema,
    nw00paap_nlarc_prdps_pdab_sffa_data_schema,
    nw00paap_nlarc_prdps_pdab_lmia_data_schema,
    nw00paap_nlarc_prdps_partval_pdab_data_schema,
    nw00paap_nlarc_prdps_partloan_pdab_data_schema,
    nw00paap_nlarc_prdps_partact_pdab_data_schema,
    fo_fund_txt_schema,
    fo_asset_txt_schema,
    fieldoffice_table_rs_raw_csv_schema,
    f986pb_mis_j986ds_detail_file_schema,
    f986pb_mis_j986cp1_tpa_data_file_schema,
    f950_rps_plan_cef_data_ewr_dat_schema,
    f950_rps_partcpnt_cef_data_ewr_dat_schema,
    f950_rps_parsdba_bal_ewr_dat_schema,
    f912pb_j912dol_p912dol5_prdcrext_lseq_schema,
    exn_xxewre01_xxewrtrxh_ng_schema,
    exn_xxewre01_xxewrtrxh_jb_schema,
    exn_xxewre01_xxewrptd_ng_schema,
    exn_xxewre01_xxewrpsd_ng_schema,
    exn_xxewre01_xxewrpsd_jb_schema,
    exn_xxewre01_xxewrpps_ng_schema,
    exn_xxewre01_xxewrpps_jb_schema,
    exn_xxewre01_xxewrppl_ng_schema,
    exn_xxewre01_xxewrppl_jb_schema,
    exn_xxewre01_xxewrpmd_jb_schema,
    exn_xxewre01_xxewrpld_ng_schema,
    exn_xxewre01_xxewrpld_jb_schema,
    exn_xxewre01_xxewrpin_jb_schema,
    exn_xxewre01_xxewrpfs_ng_schema,
    exn_xxewre01_xxewrpfs_jb_schema,
    exn_xxewre01_xxewrpfl_jb_schema,
    exn_xxewre01_xxewrpfd_ng_schema,
    exn_xxewre01_xxewrpfd_jb_schema,
    exn_xxewre01_xxewrpcb_jb_schema,
    exn_xxewre01_xxewrpbe_ng_schema,
    exn_xxewre01_xxewrpbe_jb_schema,
    exn_xxewre01_xxewrpap_ng_schema,
    exn_xxewre01_xxewrpap_jb_schema,
    exn_xxewre01_xxewrpae_ng_schema,
    exn_xxewre01_xxewrpae_jb_schema,
    exn_xxewre01_xxewrdpg_jb_schema,
    exn_xxewre01_xxewrcld_ng_schema,
    exn_xxewre01_xxewrcld_jb_schema,
    exn_xxewre01_xxewraef_ng_schema,
    exn_xxewre01_xxewraef_jb_schema,
    exn_xxadsumt_xxadhsfx_ng_schema,
    exn_xxadsumt_xxadhsfx_jb_schema,
    exn_xxadsumt_xxadhsfx_2_jb_schema,
    exn_xxadsumt_xxadhsex_ng_schema,
    exn_xxadsumt_xxadhsex_jb_schema,
    exn_xxadsumt_xxadhsex_2_jb_schema,
    exn_xxadsumt_xxadhsdx_ng_schema,
    exn_xxadsumt_xxadhsdx_jb_schema,
    exn_xxadsumt_xxadhsbx_ng_schema,
    exn_xxadsumt_xxadhsbx_jb_schema,
    exn_xxadsumt_xxadhsax_ng_schema,
    exn_xxadsumt_xxadhsax_jb_schema,
    exn_xxadahst_xxadhdrx_ng_schema,
    exn_xxadahst_xxadhdrx_jb_schema,
    exn_xxadahst_xxadhdbx_ng_schema,
    exn_xxadahst_xxadhdbx_jb_schema,
    dss_dc_producerrole_daily_dat_schema,super_omni_itd_tr_hist_jb_dat_schema,super_omni_itd_tr_hist_ng_dat_schema,div_sub_fund_bal_hist_schema,div_sub_src_bal_hist_schema,
exn_xxadsumt_xxadhsfx_2_hist_jb_schema,exn_xxadsumt_xxadhsfx_hist_jb_schema,exn_xxadsumt_xxadhsfx_hist_ng_schema,plan_expand_flag_csv_schema,super_omni_newr_histbal_jb_dat_rerun_dat_schema,exn_xxewre01_xxewrpcb_delete_jb_schema,
)


class FileParameters:
    def __init__(self, source_name, file_name, file_type, file_format, file_segmented_flag, file_load, file_header_flag,
                 primary_keys, table_name, file_segment_name=None):
        self.source_name = source_name.lower()
        self.file_name = file_name.upper()
        self.file_type = file_type.lower()
        self.file_format = file_format.lower()
        self.file_segmented_flag = file_segmented_flag
        self.file_load = file_load.lower()
        self.file_header_flag = file_header_flag
        self.table_name = table_name.lower()
        if primary_keys:
            self.primary_keys = primary_keys.split(",")
        else:
            self.primary_keys = None
        if file_segmented_flag and file_segment_name:
            self.file_segment = file_segment_name.upper().rpartition('.')[2]
        else:
            self.file_segment = None


TableNameToSchemaMapper = {
    "plan_vnq_wc_txt": plan_vnq_wc_txt_schema.schema,
    "participant_investment_product_election_vnq_wc_txt": participant_investment_product_election_vnq_wc_txt_schema.schema,
    "setit_plan_daily_wc_dat_txt": setit_plan_daily_wc_dat_txt_schema.schema,
    "participant_vnq_wc_txt": participant_vnq_wc_txt_schema.schema,
    "participant_investment_election_vnq_wc_txt": participant_investment_election_vnq_wc_txt_schema.schema,
    "employer_vnq_wc_txt": employer_vnq_wc_txt_schema.schema,
    "beneficiary_vnq_wc_txt": beneficiary_vnq_wc_txt_schema.schema,
    "transaction_vnq_wc_txt": transaction_vnq_wc_txt_schema.schema,
    "participant_distribution_vnq_wc_txt": participant_distribution_vnq_wc_txt_schema.schema,
    "participant_fund_vnq_wc_txt": participant_fund_vnq_wc_txt_schema.schema,
    "participant_fund_vnq_wc_hist_txt": participant_fund_vnq_wc_hist_txt_schema.schema,
    "participant_contribution_vnq_wc_txt": participant_contribution_vnq_wc_txt_schema.schema,
    "super_omni_newr_plan_daily_ng_dat": super_omni_newr_plan_daily_ng_dat_schema.schema,
    "super_omni_newr_plan_daily_jb_dat": super_omni_newr_plan_daily_jb_dat_schema.schema,
    "super_omni_newr_bene_daily_ng_dat": super_omni_newr_bene_daily_ng_dat_schema.schema,
    "super_omni_newr_bene_daily_jb_dat": super_omni_newr_bene_daily_jb_dat_schema.schema,
    "exn_xxewre01_xxewrptd_jb": exn_xxewre01_xxewrptd_jb_schema.schema,
    "transaction_type_csv": transaction_type_csv_schema.schema,
    "super_omni_newr_seqhist_daily_ng_dat": super_omni_newr_seqhist_daily_ng_dat_schema.schema,
    "super_omni_newr_seqhist_daily_jb_dat": super_omni_newr_seqhist_daily_jb_dat_schema.schema,
    "super_omni_newr_plan_mindist_daily_ng_dat": super_omni_newr_plan_mindist_daily_ng_dat_schema.schema,
    "super_omni_newr_plan_ins_daily_ng_dat": super_omni_newr_plan_ins_daily_ng_dat_schema.schema,
    "super_omni_newr_plan_divsub_daily_ng_dat": super_omni_newr_plan_divsub_daily_ng_dat_schema.schema,
    "super_omni_newr_planwdrl_daily_ng_dat": super_omni_newr_planwdrl_daily_ng_dat_schema.schema,
    "super_omni_newr_planwdrl_daily_jb_dat": super_omni_newr_planwdrl_daily_jb_dat_schema.schema,
    "super_omni_newr_planvesting_daily_ng_dat": super_omni_newr_planvesting_daily_ng_dat_schema.schema,
    "super_omni_newr_planvesting_daily_jb_dat": super_omni_newr_planvesting_daily_jb_dat_schema.schema,
    "super_omni_newr_partsrcval_daily_ng_dat": super_omni_newr_partsrcval_daily_ng_dat_schema.schema,
    "super_omni_newr_particpantaccount_daily_ng_dat": super_omni_newr_particpantaccount_daily_ng_dat_schema.schema,
    "super_omni_newr_particpantaccount_daily_jb_dat": super_omni_newr_particpantaccount_daily_jb_dat_schema.schema,
    "super_omni_newr_partgaabal_monthly_ng_dat": super_omni_newr_partgaabal_monthly_ng_dat_schema.schema,
    "super_omni_newr_partacctms_daily_ng_dat": super_omni_newr_partacctms_daily_ng_dat_schema.schema,
    "super_omni_newr_partacctms_daily_jb_dat": super_omni_newr_partacctms_daily_jb_dat_schema.schema,
    "super_omni_newr_loanval_daily_ng_dat": super_omni_newr_loanval_daily_ng_dat_schema.schema,
    "super_omni_newr_lifeval_monthly_ng_dat": super_omni_newr_lifeval_monthly_ng_dat_schema.schema,
    "super_omni_newr_histbal_ng_dat": super_omni_newr_histbal_ng_dat_schema.schema,
    "super_omni_newr_histbal_jb_dat": super_omni_newr_histbal_jb_dat_schema.schema,
    "stars_daily_contact_dat": stars_daily_contact_dat_schema.schema,
    "ssn_output_ng": ssn_output_ng_schema.schema,
    "ssn_output_jb": ssn_output_jb_schema.schema,
    "slx_tpa_common_daily_dat": slx_tpa_common_daily_dat_schema.schema,
    "presto_plan_daily_dat": presto_plan_daily_dat_schema.schema,
    "premier_fund_translation_csv": premier_fund_translation_csv_schema.schema,
    "pdab_sponsor_csv": pdab_sponsor_csv_schema.schema,
    "pdab_role_code_helper_csv": pdab_role_code_helper_csv_schema.schema,
    "pdab_product_helper_csv": pdab_product_helper_csv_schema.schema,
    "pdab_money_source_helper_csv": pdab_money_source_helper_csv_schema.schema,
    "pdab_market_segment_csv": pdab_market_segment_csv_schema.schema,
    "pdab_auto_method_csv": pdab_auto_method_csv_schema.schema,
    "pdab_automation_type_csv": pdab_automation_type_csv_schema.schema,
    "ods_retirement_account": ods_retirement_account_schema.schema,
    "nw00paap_nldss_prdps_ps50_prdcrext_lx_seq": nw00paap_nldss_prdps_ps50_prdcrext_lx_seq_schema.schema,
    "nw00paap_nlarc_prdps_plan_pdab_data": nw00paap_nlarc_prdps_plan_pdab_data_schema.schema,
    "nw00paap_nlarc_prdps_pdab_sffa_data": nw00paap_nlarc_prdps_pdab_sffa_data_schema.schema,
    "nw00paap_nlarc_prdps_pdab_lmia_data": nw00paap_nlarc_prdps_pdab_lmia_data_schema.schema,
    "nw00paap_nlarc_prdps_partval_pdab_data": nw00paap_nlarc_prdps_partval_pdab_data_schema.schema,
    "nw00paap_nlarc_prdps_partloan_pdab_data": nw00paap_nlarc_prdps_partloan_pdab_data_schema.schema,
    "nw00paap_nlarc_prdps_partact_pdab_data": nw00paap_nlarc_prdps_partact_pdab_data_schema.schema,
    "fo_fund_txt": fo_fund_txt_schema.schema,
    "fo_asset_txt": fo_asset_txt_schema.schema,
    "fieldoffice_table_rs_raw_csv": fieldoffice_table_rs_raw_csv_schema.schema,
    "f986pb_mis_j986ds_detail_file": f986pb_mis_j986ds_detail_file_schema.schema,
    "f986pb_mis_j986cp1_tpa_data_file": f986pb_mis_j986cp1_tpa_data_file_schema.schema,
    "f950_rps_plan_cef_data_ewr_dat": f950_rps_plan_cef_data_ewr_dat_schema.schema,
    "f950_rps_partcpnt_cef_data_ewr_dat": f950_rps_partcpnt_cef_data_ewr_dat_schema.schema,
    "f950_rps_parsdba_bal_ewr_dat": f950_rps_parsdba_bal_ewr_dat_schema.schema,
    "f912pb_j912dol_p912dol5_prdcrext_lseq": f912pb_j912dol_p912dol5_prdcrext_lseq_schema.schema,
    "exn_xxewre01_xxewrtrxh_ng": exn_xxewre01_xxewrtrxh_ng_schema.schema,
    "exn_xxewre01_xxewrtrxh_jb": exn_xxewre01_xxewrtrxh_jb_schema.schema,
    "exn_xxewre01_xxewrptd_ng": exn_xxewre01_xxewrptd_ng_schema.schema,
    "exn_xxewre01_xxewrpsd_ng": exn_xxewre01_xxewrpsd_ng_schema.schema,
    "exn_xxewre01_xxewrpsd_jb": exn_xxewre01_xxewrpsd_jb_schema.schema,
    "exn_xxewre01_xxewrpps_ng": exn_xxewre01_xxewrpps_ng_schema.schema,
    "exn_xxewre01_xxewrpps_jb": exn_xxewre01_xxewrpps_jb_schema.schema,
    "exn_xxewre01_xxewrppl_ng": exn_xxewre01_xxewrppl_ng_schema.schema,
    "exn_xxewre01_xxewrppl_jb": exn_xxewre01_xxewrppl_jb_schema.schema,
    "exn_xxewre01_xxewrpmd_jb": exn_xxewre01_xxewrpmd_jb_schema.schema,
    "exn_xxewre01_xxewrpld_ng": exn_xxewre01_xxewrpld_ng_schema.schema,
    "exn_xxewre01_xxewrpld_jb": exn_xxewre01_xxewrpld_jb_schema.schema,
    "exn_xxewre01_xxewrpin_jb": exn_xxewre01_xxewrpin_jb_schema.schema,
    "exn_xxewre01_xxewrpfs_ng": exn_xxewre01_xxewrpfs_ng_schema.schema,
    "exn_xxewre01_xxewrpfs_jb": exn_xxewre01_xxewrpfs_jb_schema.schema,
    "exn_xxewre01_xxewrpfl_jb": exn_xxewre01_xxewrpfl_jb_schema.schema,
    "exn_xxewre01_xxewrpfd_ng": exn_xxewre01_xxewrpfd_ng_schema.schema,
    "exn_xxewre01_xxewrpfd_jb": exn_xxewre01_xxewrpfd_jb_schema.schema,
    "exn_xxewre01_xxewrpcb_jb": exn_xxewre01_xxewrpcb_jb_schema.schema,
    "exn_xxewre01_xxewrpbe_ng": exn_xxewre01_xxewrpbe_ng_schema.schema,
    "exn_xxewre01_xxewrpbe_jb": exn_xxewre01_xxewrpbe_jb_schema.schema,
    "exn_xxewre01_xxewrpap_ng": exn_xxewre01_xxewrpap_ng_schema.schema,
    "exn_xxewre01_xxewrpap_jb": exn_xxewre01_xxewrpap_jb_schema.schema,
    "exn_xxewre01_xxewrpae_ng": exn_xxewre01_xxewrpae_ng_schema.schema,
    "exn_xxewre01_xxewrpae_jb": exn_xxewre01_xxewrpae_jb_schema.schema,
    "exn_xxewre01_xxewrdpg_jb": exn_xxewre01_xxewrdpg_jb_schema.schema,
    "exn_xxewre01_xxewrcld_ng": exn_xxewre01_xxewrcld_ng_schema.schema,
    "exn_xxewre01_xxewrcld_jb": exn_xxewre01_xxewrcld_jb_schema.schema,
    "exn_xxewre01_xxewraef_ng": exn_xxewre01_xxewraef_ng_schema.schema,
    "exn_xxewre01_xxewraef_jb": exn_xxewre01_xxewraef_jb_schema.schema,
    "exn_xxadsumt_xxadhsfx_ng": exn_xxadsumt_xxadhsfx_ng_schema.schema,
    "exn_xxadsumt_xxadhsfx_jb": exn_xxadsumt_xxadhsfx_jb_schema.schema,
    "exn_xxadsumt_xxadhsfx_2_jb": exn_xxadsumt_xxadhsfx_2_jb_schema.schema,
    "exn_xxadsumt_xxadhsex_ng": exn_xxadsumt_xxadhsex_ng_schema.schema,
    "exn_xxadsumt_xxadhsex_jb": exn_xxadsumt_xxadhsex_jb_schema.schema,
    "exn_xxadsumt_xxadhsex_2_jb": exn_xxadsumt_xxadhsex_2_jb_schema.schema,
    "exn_xxadsumt_xxadhsdx_ng": exn_xxadsumt_xxadhsdx_ng_schema.schema,
    "exn_xxadsumt_xxadhsdx_jb": exn_xxadsumt_xxadhsdx_jb_schema.schema,
    "exn_xxadsumt_xxadhsbx_ng": exn_xxadsumt_xxadhsbx_ng_schema.schema,
    "exn_xxadsumt_xxadhsbx_jb": exn_xxadsumt_xxadhsbx_jb_schema.schema,
    "exn_xxadsumt_xxadhsax_ng": exn_xxadsumt_xxadhsax_ng_schema.schema,
    "exn_xxadsumt_xxadhsax_jb": exn_xxadsumt_xxadhsax_jb_schema.schema,
    "exn_xxadahst_xxadhdrx_ng": exn_xxadahst_xxadhdrx_ng_schema.schema,
    "exn_xxadahst_xxadhdrx_jb": exn_xxadahst_xxadhdrx_jb_schema.schema,
    "exn_xxadahst_xxadhdbx_ng": exn_xxadahst_xxadhdbx_ng_schema.schema,
    "exn_xxadahst_xxadhdbx_jb": exn_xxadahst_xxadhdbx_jb_schema.schema,
    "dss_dc_producerrole_daily_dat": dss_dc_producerrole_daily_dat_schema.schema,
    "super_omni_itd_tr_hist_ng_dat": super_omni_itd_tr_hist_jb_dat_schema.schema,
    "super_omni_itd_tr_hist_jb_dat": super_omni_itd_tr_hist_ng_dat_schema.schema,
    "exn_xxadsumt_xxadhsfx_hist_ng": exn_xxadsumt_xxadhsfx_hist_ng_schema.schema,
    "exn_xxadsumt_xxadhsfx_hist_jb": exn_xxadsumt_xxadhsfx_hist_jb_schema.schema,
    "exn_xxadsumt_xxadhsfx_2_hist_jb": exn_xxadsumt_xxadhsfx_2_hist_jb_schema.schema,
    "div_sub_src_bal_hist": div_sub_src_bal_hist_schema.schema,
    "div_sub_fund_bal_hist": div_sub_fund_bal_hist_schema.schema,
    "plan_expand_flag_csv": plan_expand_flag_csv_schema.schema,
    "exn_xxewre01_xxewrpcb_delete_jb": exn_xxewre01_xxewrpcb_delete_jb_schema.schema,
    "super_omni_newr_histbal_jb_dat_rerun_dat":super_omni_newr_histbal_jb_dat_rerun_dat_schema.schema,
}
